<?php

return [
    'brand' => [
        'name' => 'LM Workshop',
        'legal_name' => 'LM Workshop',
        'alternate_names' => [
            'LM Workshop Maldives',
            'LM Workshop Malé',
            'LMWorkshop',
            'LMW',
        ],
        'tagline' => 'Engineering You Can Count On',
        'description' => 'LM Workshop is an engineering company in the Maldives providing reliable marine, industrial and commercial engineering support.',
        'phone' => '+960 XXX XXXX',
        'whatsapp' => '+960 XXX XXXX',
        'email' => 'info@lmworkshop.com',
        'website' => 'www.lmworkshop.com',
        'location' => 'Malé, Maldives',
        'same_as' => [
            // Add social profile URLs when available, e.g. Facebook / LinkedIn / Instagram
        ],
    ],

    'seo' => [
        'og_images' => [
            'home' => 'hero',
            'about' => 'aboutHero',
            'services' => 'servicesHero',
            'industries' => 'industriesHero',
            'why' => 'whyHero',
            'capability' => 'capabilityHero',
            'how-we-work' => 'howWeWorkHero',
            'team' => 'teamHero',
            'contact' => 'weldingAdrian',
        ],
    ],

    'contact' => [
        'equipment_types' => [
            'Marine Engine / Vessel',
            'Generator / Power System',
            'Pump / Hydraulic System',
            'Electrical Panel / Control System',
            'Heavy Equipment / Construction Machinery',
            'Fabrication / Structural',
            'Fuel / Water System',
            'HVAC / Refrigeration',
            'Other',
        ],
        'urgency_levels' => [
            'emergency' => 'Emergency — equipment down now',
            'urgent' => 'Urgent — within 24–48 hours',
            'planned' => 'Planned — scheduled maintenance or project',
            'general' => 'General enquiry',
        ],
    ],

    'nav' => [
        ['label' => 'Home', 'route' => 'home'],
        ['label' => 'About Us', 'route' => 'about'],
        ['label' => 'Why Choose Us', 'route' => 'why'],
        ['label' => 'Industries', 'route' => 'industries'],
        ['label' => 'Services', 'route' => 'services'],
        ['label' => 'Capability', 'route' => 'capability'],
        ['label' => 'How We Work', 'route' => 'how-we-work'],
        ['label' => 'Team', 'route' => 'team'],
        ['label' => 'Contact', 'route' => 'contact'],
    ],

    'images' => [
        'logo' => 'images/logo/LMW Logo H Alt.svg',
        'favicon' => 'images/favicon/favicon.svg',
        'hero' => 'images/homepage/ChatGPT Image Jul 7, 2026, 10_20_17 AM.png',
        'heroVideo' => 'images/homepage/Main.webm',
        'reliabilityBg' => 'images/home/ChatGPT Image Jul 7, 2026, 02_56_52 PM.png',
        'aboutHero' => 'images/aboutus/ChatGPT Image Jul 7, 2026, 11_14_42 AM.png',
        'servicesHero' => 'images/services/ChatGPT Image Jul 7, 2026, 11_23_25 AM.png',
        'industriesHero' => 'images/industries/ChatGPT Image Jul 7, 2026, 11_28_23 AM.png',
        'whyHero' => 'images/why_choose_us/ChatGPT Image Jul 7, 2026, 11_32_47 AM.png',
        'capabilityHero' => 'images/capability/ChatGPT Image Jul 7, 2026, 11_40_01 AM.png',
        'howWeWorkHero' => 'images/How_We_Work/ChatGPT Image Jul 7, 2026, 11_44_19 AM.png',
        'teamHero' => 'images/team/ChatGPT Image Jul 7, 2026, 12_13_22 PM.png',
        'workerGears' => 'https://images.unsplash.com/photo-1759692071969-c32285cffc40?w=900&h=700&fit=crop&auto=format',
        'welding' => 'https://images.unsplash.com/photo-1745448797900-35d08e85e9db?w=900&h=700&fit=crop&auto=format',
        'weldingSparks' => 'https://images.unsplash.com/photo-1738162837369-a2beec3a1d47?w=900&h=600&fit=crop&auto=format',
        'weldingAdrian' => 'https://images.unsplash.com/photo-1776159904891-e7b213b8198f?w=1920&h=900&fit=crop&auto=format',
        'marine' => 'images/home/Marine & Vessel Operators.webp',
        'powerPlant' => 'images/home/Industrial Facilities.webp',
        'factory' => 'https://images.unsplash.com/photo-1636887584784-954392022b75?w=900&h=600&fit=crop&auto=format',
        'construction' => 'https://images.unsplash.com/photo-1583024011792-b165975b52f5?w=900&h=600&fit=crop&auto=format',
        'maldives' => 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=900&h=600&fit=crop&auto=format',
        'valves' => 'https://images.unsplash.com/photo-1759148414485-5f624fe9d1ea?w=900&h=600&fit=crop&auto=format',
        'engineer' => 'https://images.unsplash.com/photo-1595856898575-9d187bd32fd6?w=900&h=700&fit=crop&auto=format',
        'industrial' => 'https://images.unsplash.com/photo-1765021689980-a1ce75fdee3a?w=900&h=600&fit=crop&auto=format',
        'excavator' => 'https://images.unsplash.com/photo-1603814929877-d5d927322656?w=900&h=600&fit=crop&auto=format',
        'workerClimb' => 'https://images.unsplash.com/photo-1771915958294-8f509abc0212?w=900&h=700&fit=crop&auto=format',
        'machine' => 'https://images.unsplash.com/photo-1729997310239-96ffef7a5cb5?w=900&h=600&fit=crop&auto=format',
        'islandBoat' => 'https://images.unsplash.com/photo-1741159273235-0a1466c043cd?w=900&h=600&fit=crop&auto=format',
    ],

    'services' => [
        [
            'slug' => 'marine-engineering',
            'icon' => 'anchor',
            'title' => 'Marine Engineering',
            'desc' => 'Inspection, servicing, diagnostics, overhauls and repairs for marine engines and vessels.',
            'hero' => 'marine',
            'summary' => 'LM Workshop keeps vessels and marine propulsion systems operating reliably across the Maldives — from resort dhonis and supply boats to commercial fleets and harbour craft.',
            'capabilities' => [
                'Engine diagnostics, fault finding and performance testing',
                'Planned servicing, oil changes and filter replacement programmes',
                'Gearbox, shafting and propulsion system repairs',
                'Cooling, exhaust and fuel system troubleshooting',
                'Emergency breakdown response at harbour or anchorage',
                'Technical reports and maintenance recommendations',
            ],
            'equipment' => [
                'Main and auxiliary marine diesel engines',
                'Outboard and inboard propulsion units',
                'Gearboxes, shafts and propellers',
                'Marine generators and battery systems',
                'Hydraulic steering and deck machinery',
                'Cooling pumps, heat exchangers and sea water systems',
            ],
            'projects' => [
                ['title' => 'Resort Fleet Preventive Programme', 'detail' => 'Scheduled servicing and breakdown support for a multi-vessel resort transport fleet across three atolls.'],
                ['title' => 'Commercial Supply Vessel Overhaul', 'detail' => 'Engine diagnostics, component replacement and sea trials to restore full operational capacity.'],
                ['title' => 'Harbour Craft Emergency Repair', 'detail' => 'Rapid on-site response to propulsion failure, returning vessel to service within 48 hours.'],
            ],
            'keywords' => ['marine engineering Maldives', 'vessel maintenance', 'marine engine repair'],
        ],
        [
            'slug' => 'power-systems',
            'icon' => 'zap',
            'title' => 'Power Systems',
            'desc' => 'Maintenance, repairs and technical support for generators, powerhouse systems and synchronisation equipment.',
            'hero' => 'powerPlant',
            'summary' => 'Reliable power is critical for resorts, industrial sites and commercial facilities. LM Workshop delivers generator maintenance, powerhouse support and synchronisation expertise across the Maldives.',
            'capabilities' => [
                'Generator load testing and performance verification',
                'Alternator, AVR and control panel troubleshooting',
                'Synchronisation and paralleling system support',
                'Fuel system inspection and corrective maintenance',
                'Planned powerhouse maintenance programmes',
                'Emergency generator breakdown response',
            ],
            'equipment' => [
                'Diesel generators from 20 kVA to multi-MW sets',
                'Automatic transfer switches and sync panels',
                'Powerhouse switchgear and distribution boards',
                'Voltage regulators and engine control modules',
                'Fuel day tanks, transfer pumps and filtration',
                'Exhaust, ventilation and acoustic systems',
            ],
            'projects' => [
                ['title' => 'Resort Powerhouse Maintenance', 'detail' => 'Ongoing generator servicing and load testing for a luxury resort with dual powerhouse redundancy.'],
                ['title' => 'Industrial Plant Generator Overhaul', 'detail' => 'Major service and control system calibration for a production facility standby power unit.'],
                ['title' => 'Synchronisation Panel Upgrade Support', 'detail' => 'Engineering support during panel replacement and commissioning of parallel generator operation.'],
            ],
            'keywords' => ['generator maintenance Maldives', 'powerhouse servicing', 'generator repair Malé'],
        ],
        [
            'slug' => 'mechanical-electrical',
            'icon' => 'wrench',
            'title' => 'Mechanical & Electrical',
            'desc' => 'Engineering solutions for pumps, control systems, electrical infrastructure, automation and utility systems.',
            'hero' => 'machine',
            'summary' => 'From pumps and HVAC to electrical panels and automation, LM Workshop provides integrated mechanical and electrical engineering support for operational facilities.',
            'capabilities' => [
                'Pump alignment, servicing and performance restoration',
                'Motor testing, rewiring and control circuit repairs',
                'PLC, sensor and instrumentation troubleshooting',
                'Distribution board inspection and corrective works',
                'Pipework modifications and utility system upgrades',
                'Preventive maintenance planning for mechanical assets',
            ],
            'equipment' => [
                'Centrifugal and submersible pump sets',
                'Electric motors, starters and VFD drives',
                'Control panels, MCCs and distribution boards',
                'HVAC compressors, fans and chilled water systems',
                'Valves, actuators and instrumentation',
                'Compressed air and utility pipework',
            ],
            'projects' => [
                ['title' => 'Resort Water Pump Overhaul', 'detail' => 'Replacement of worn impeller assemblies and control upgrades for a high-demand desalination feed system.'],
                ['title' => 'Industrial Motor & Panel Repair', 'detail' => 'Fault diagnosis and restoration of a production line drive system after electrical surge damage.'],
                ['title' => 'Utility System Preventive Programme', 'detail' => 'Quarterly inspection and servicing of pumps, valves and electrical assets across a commercial facility.'],
            ],
            'keywords' => ['mechanical electrical engineering Maldives', 'pump repair', 'electrical maintenance'],
        ],
        [
            'slug' => 'fabrication',
            'icon' => 'hammer',
            'title' => 'Fabrication',
            'desc' => 'Steel, stainless steel and aluminium fabrication, structural repairs and custom engineering works.',
            'hero' => 'weldingSparks',
            'summary' => 'When off-the-shelf parts will not do, LM Workshop fabricates and repairs structural and mechanical components to keep your operations running.',
            'capabilities' => [
                'Custom steel, stainless and aluminium fabrication',
                'Structural repairs for platforms, frames and supports',
                'Pipework fabrication and modification',
                'Tank repairs, patching and reinforcement',
                'On-site welding and fitting for remote locations',
                'Fabrication from drawings or site measurements',
            ],
            'equipment' => [
                'Structural steel and platform components',
                'Stainless process pipework and manifolds',
                'Aluminium marine and architectural fabrications',
                'Guards, brackets, mounts and custom frames',
                'Tank sections, hatches and access structures',
                'Wear plates, chutes and industrial fittings',
            ],
            'projects' => [
                ['title' => 'Resort Jetty Structural Repair', 'detail' => 'Fabrication and installation of replacement steel members for a damaged guest transfer jetty.'],
                ['title' => 'Industrial Pipework Modification', 'detail' => 'Custom stainless pipe fabrication for a process line upgrade at an industrial facility.'],
                ['title' => 'Vessel Deck Fabrication', 'detail' => 'Design and fabrication of custom mounting structures for marine equipment installation.'],
            ],
            'keywords' => ['steel fabrication Maldives', 'welding services', 'structural repair'],
        ],
        [
            'slug' => 'heavy-equipment',
            'icon' => 'truck',
            'title' => 'Heavy Equipment',
            'desc' => 'Maintenance and repairs for construction machinery, industrial diesel engines and hydraulic equipment.',
            'hero' => 'excavator',
            'summary' => 'Construction and industrial sites depend on heavy machinery. LM Workshop maintains and repairs excavators, loaders, cranes and hydraulic systems throughout the Maldives.',
            'capabilities' => [
                'Hydraulic system diagnosis and hose/component replacement',
                'Undercarriage, boom and attachment inspections',
                'Diesel engine servicing for construction plant',
                'Breakdown response for critical site equipment',
                'Preventive maintenance scheduling and reporting',
                'Component removal, refit and operational testing',
            ],
            'equipment' => [
                'Excavators, loaders and backhoe loaders',
                'Cranes, hoists and lifting equipment',
                'Compactors, rollers and site plant',
                'Hydraulic pumps, cylinders and control valves',
                'Industrial diesel engines and power packs',
                'Attachments, buckets and quick-hitch assemblies',
            ],
            'projects' => [
                ['title' => 'Construction Fleet Servicing', 'detail' => 'Scheduled hydraulic and engine maintenance for a contractor fleet operating across multiple island projects.'],
                ['title' => 'Excavator Hydraulic Rebuild', 'detail' => 'Full hydraulic system overhaul and pressure testing to restore machine productivity on a major build.'],
                ['title' => 'Emergency Crane Breakdown', 'detail' => 'On-site fault finding and repair to return lifting equipment to safe operation.'],
            ],
            'keywords' => ['heavy equipment maintenance Maldives', 'construction machinery repair'],
        ],
        [
            'slug' => 'fuel-water-systems',
            'icon' => 'droplets',
            'title' => 'Fuel & Water Systems',
            'desc' => 'Design, installation, maintenance and modification of storage and distribution systems.',
            'hero' => 'valves',
            'summary' => 'Fuel and water systems must be safe, reliable and compliant. LM Workshop designs, installs and maintains storage, transfer and distribution systems for resorts and industrial clients.',
            'capabilities' => [
                'Tank inspection, cleaning coordination and repairs',
                'Fuel transfer pump and filtration system servicing',
                'Pipework installation and leak remediation',
                'Water distribution and booster pump support',
                'System modifications for capacity or layout changes',
                'Operational safety checks and maintenance documentation',
            ],
            'equipment' => [
                'Diesel and petrol storage tanks and bunds',
                'Fuel transfer pumps, filters and dispensers',
                'Water storage tanks and level control systems',
                'Booster pumps and pressurisation sets',
                'Pipework, valves and isolation manifolds',
                'Day tanks and generator fuel feed systems',
            ],
            'projects' => [
                ['title' => 'Resort Fuel System Upgrade', 'detail' => 'Modification of generator fuel feed lines and filter upgrades for improved reliability.'],
                ['title' => 'Industrial Water Distribution Repair', 'detail' => 'Pump replacement and pipework repairs for a facility process water network.'],
                ['title' => 'Tank Farm Maintenance Programme', 'detail' => 'Scheduled inspection and servicing of storage and transfer equipment at a logistics site.'],
            ],
            'keywords' => ['fuel system maintenance Maldives', 'water system engineering'],
        ],
        [
            'slug' => 'spare-parts-support',
            'icon' => 'package',
            'title' => 'Spare Parts & Technical Support',
            'desc' => 'Technical verification, parts identification, procurement coordination and installation support.',
            'hero' => 'workerGears',
            'summary' => 'Wrong parts cost time and money. LM Workshop helps identify, source and verify components so your equipment gets back online faster.',
            'capabilities' => [
                'Parts identification from samples, photos or equipment data',
                'Technical cross-reference and specification verification',
                'Procurement coordination with suppliers and freight agents',
                'Installation support and fitment checks on site',
                'Obsolescence advice and alternative component options',
                'Maintenance kit planning for critical equipment',
            ],
            'equipment' => [
                'Engine and generator consumables and service kits',
                'Pump seals, impellers and mechanical components',
                'Electrical contactors, sensors and control parts',
                'Hydraulic hoses, fittings and cylinder seals',
                'Filters, belts and drive components',
                'Fabricated alternatives when OEM parts are unavailable',
            ],
            'projects' => [
                ['title' => 'Marine Engine Parts Coordination', 'detail' => 'Identification and expedited sourcing of critical engine components for a stranded commercial vessel.'],
                ['title' => 'Generator Overhaul Kit Supply', 'detail' => 'Compiled and verified major service kit for a resort powerhouse planned shutdown.'],
                ['title' => 'Pump Component Replacement', 'detail' => 'Technical verification and installation support for custom-fit pump seal assemblies.'],
            ],
            'keywords' => ['engineering spare parts Maldives', 'technical parts support'],
        ],
        [
            'slug' => 'preventive-maintenance',
            'icon' => 'shield-check',
            'title' => 'Preventive Maintenance',
            'desc' => 'Planned maintenance programmes designed to reduce downtime, extend equipment life and improve operational reliability.',
            'hero' => 'servicesHero',
            'summary' => 'Prevent problems before they stop your operation. LM Workshop designs and delivers planned maintenance programmes tailored to your equipment, site and operating schedule.',
            'capabilities' => [
                'Asset surveys and maintenance priority assessments',
                'Customised PM schedules by equipment type and usage',
                'Routine inspection, servicing and condition reporting',
                'Trend tracking for wear, vibration and performance',
                'Coordination of shutdowns and island visit planning',
                'Documentation for audits, insurers and management reporting',
            ],
            'equipment' => [
                'Marine engines and vessel systems',
                'Generators and powerhouse equipment',
                'Pumps, compressors and utility plant',
                'Heavy equipment and construction machinery',
                'Electrical distribution and control assets',
                'Fuel, water and process support systems',
            ],
            'projects' => [
                ['title' => 'Resort Engineering PM Programme', 'detail' => 'Annual planned maintenance covering generators, pumps and marine assets across a multi-island resort operation.'],
                ['title' => 'Industrial Facility Maintenance Plan', 'detail' => 'Developed asset register and quarterly PM schedule for a production facility powerhouse and utilities.'],
                ['title' => 'Vessel Fleet Scheduled Servicing', 'detail' => 'Rolling maintenance programme for a commercial operator with coordinated port visits and reporting.'],
            ],
            'keywords' => ['preventive maintenance Maldives', 'planned maintenance programme'],
        ],
    ],

    'industries' => [
        ['title' => 'Resorts & Hospitality', 'desc' => 'Supporting guest operations through reliable powerhouse systems, marine fleets, mechanical infrastructure and preventive maintenance.', 'img' => 'maldives'],
        ['title' => 'Marine & Vessel Operators', 'desc' => 'Maintaining vessel reliability through marine engineering, diagnostics, repairs, overhauls and technical support.', 'img' => 'marine'],
        ['title' => 'Construction Companies', 'desc' => 'Supporting construction projects with fabrication, heavy equipment maintenance and mechanical engineering solutions.', 'img' => 'construction'],
        ['title' => 'Industrial Facilities', 'desc' => 'Providing engineering support for generators, pumps, mechanical systems, electrical infrastructure and operational equipment.', 'img' => 'powerPlant'],
        ['title' => 'Commercial Businesses', 'desc' => 'Maintaining critical building systems, utilities and engineering infrastructure to minimise operational disruption.', 'img' => 'valves'],
        ['title' => 'Government & Infrastructure', 'desc' => 'Delivering dependable engineering support for public infrastructure, utilities and technical projects.', 'img' => 'factory'],
    ],

    'industries_value' => [
        ['heading' => 'One Engineering Partner', 'body' => 'Rather than managing multiple contractors, LM Workshop provides multi-disciplinary engineering support through a single accountable partner.'],
        ['heading' => 'Operational Understanding', 'body' => 'We work closely with each client to understand their specific operational environment, equipment, schedules and maintenance requirements.'],
        ['heading' => 'Maldives Expertise', 'body' => 'Deep experience operating in the unique logistical and environmental conditions of the Maldives, including remote island and marine environments.'],
    ],

    'why' => [
        ['icon' => 'clock', 'title' => 'Reliable Response', 'body' => 'We recognise the operational impact of downtime and respond with urgency, professionalism and practical engineering solutions.', 'detail' => 'When critical equipment fails, every hour matters. Our team mobilises quickly, arrives prepared and focuses on restoring operations as efficiently as possible.'],
        ['icon' => 'settings', 'title' => 'Practical Engineering', 'body' => 'Our recommendations are based on real-world engineering experience, providing solutions that work in operational environments—not just on paper.', 'detail' => "We don't over-engineer or under-deliver. Our solutions are designed around your actual operating conditions, equipment age, budget constraints and long-term maintenance strategy."],
        ['icon' => 'layers', 'title' => 'Multi-Disciplinary Expertise', 'body' => 'Marine, mechanical, electrical and fabrication capabilities are available through a single engineering partner, simplifying project coordination.', 'detail' => 'Rather than coordinating multiple contractors for different disciplines, LM Workshop provides a single point of accountability across all engineering requirements.'],
        ['icon' => 'star', 'title' => 'Quality Workmanship', 'body' => 'Every project is approached with attention to detail, safety and professional engineering standards.', 'detail' => 'From straightforward maintenance to complex engineering projects, we apply the same rigorous standards to every task we undertake.'],
        ['icon' => 'message-square', 'title' => 'Transparent Communication', 'body' => 'Clear scopes of work, realistic timelines and regular updates ensure clients remain informed throughout every project.', 'detail' => 'We provide written proposals, agreed scopes of work, progress updates and clear completion reports — so you always know where your project stands.'],
        ['icon' => 'handshake', 'title' => 'Long-Term Partnership', 'body' => "We measure success not by completing individual jobs, but by building trusted relationships that support our clients' operations for years to come.", 'detail' => 'Our goal is to become an extension of your operations team — a trusted engineering partner who understands your equipment, your systems and your priorities.'],
    ],

    'why_promise' => [
        'Written proposals and agreed scopes of work',
        'Experienced engineers deployed on every project',
        'Quality checks before project completion and handover',
        'Follow-up support to ensure lasting performance',
        'Preventive maintenance planning to reduce future risk',
    ],

    'why_home' => [
        ['icon' => 'clock', 'title' => 'Reliable Response', 'desc' => 'We respond with urgency, professionalism and practical engineering solutions.'],
        ['icon' => 'settings', 'title' => 'Practical Engineering', 'desc' => 'Real-world solutions that work in operational environments — not just on paper.'],
        ['icon' => 'layers', 'title' => 'Multi-Disciplinary Expertise', 'desc' => 'Marine, mechanical, electrical and fabrication capabilities through one partner.'],
        ['icon' => 'star', 'title' => 'Quality Workmanship', 'desc' => 'Every project approached with attention to detail, safety and professional standards.'],
        ['icon' => 'message-square', 'title' => 'Transparent Communication', 'desc' => 'Clear scopes of work, realistic timelines and regular updates throughout.'],
        ['icon' => 'handshake', 'title' => 'Long-Term Partnership', 'desc' => 'Building trusted relationships that support your operations for years to come.'],
    ],

    'process' => [
        ['icon' => 'message-circle', 'title' => 'Consultation', 'body' => 'Understanding your operational requirements.'],
        ['icon' => 'search', 'title' => 'Site Assessment', 'body' => 'Inspecting equipment, identifying issues and evaluating project requirements.'],
        ['icon' => 'file-text', 'title' => 'Engineering Proposal', 'body' => 'Providing a clear scope of work, recommendations, timelines and commercial proposal.'],
        ['icon' => 'wrench', 'title' => 'Execution', 'body' => 'Delivering engineering services using experienced personnel, appropriate equipment and professional workmanship.'],
        ['icon' => 'check-square', 'title' => 'Testing & Handover', 'body' => 'Verifying performance, ensuring quality and completing project handover.'],
        ['icon' => 'headset', 'title' => 'Ongoing Support', 'body' => 'Providing continued technical assistance, maintenance and long-term engineering partnership.'],
    ],

    'capability_gallery' => [
        ['label' => 'Marine engines', 'img' => 'marine'],
        ['label' => 'Generator servicing', 'img' => 'powerPlant'],
        ['label' => 'Electrical panels', 'img' => 'machine'],
        ['label' => 'Fabrication workshop', 'img' => 'weldingSparks'],
        ['label' => 'Pump systems', 'img' => 'valves'],
        ['label' => 'Heavy equipment', 'img' => 'excavator'],
        ['label' => 'Welding', 'img' => 'welding'],
        ['label' => 'Engineers on-site', 'img' => 'workerGears'],
    ],

    'team' => [
        ['name' => 'Team Member 01', 'role' => 'Head of Marine Engineering', 'years' => '18 Years Experience', 'spec' => 'Marine Propulsion & Vessel Systems', 'img' => 'images/team/member/Team member 01.jpeg'],
        ['name' => 'Team Member 02', 'role' => 'Senior Power Systems Engineer', 'years' => '14 Years Experience', 'spec' => 'Generators & Powerhouse Systems', 'img' => 'images/team/member/Team member 02.jpeg'],
        ['name' => 'Team Member 03', 'role' => 'Mechanical & Electrical Engineer', 'years' => '12 Years Experience', 'spec' => 'Pumps, HVAC & Electrical Infrastructure', 'img' => 'images/team/member/Team member 03.jpeg'],
    ],

    'team_values' => [
        ['heading' => 'Safety First', 'body' => 'Every engineer is trained in safe work practices and complies with safety requirements across all project environments.'],
        ['heading' => 'Technical Excellence', 'body' => 'Continuous learning and on-the-job experience ensure our team stays current with engineering standards and best practices.'],
        ['heading' => 'Accountable Professionals', 'body' => 'Our engineers take pride in their work and take responsibility for the quality of every project they deliver.'],
    ],

    'contact_labels' => ['Phone', 'WhatsApp', 'Email', 'Website', 'QR Code'],
];
